### ISSUE TITLE
Error report1: Missing code in Xamarin.FormsBook.Toolkit.Vector2

### ISSUE THREAD

**Issue by JimSEOW** [xamarin/xamarin-forms-book-samples#2]
Chapter 27: Chapter27/BouncingBall/BouncingBall/BouncingBall/BouncingBallPage.xaml.cs
`vector -= 2 * Vector2.DotProduct(vector, wall) * wall;`

Vector2 has no DotProduct function

**Comment by mayankmetha** [comment]
import toolkit provided in this link https://github.com/xamarin/xamarin-forms-book-samples/tree/master/Libraries/Xamarin.FormsBook.Toolkit to your project 
Vector2.cs file will solve the issue
